# Generated by Django 2.2 on 2019-04-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=40)),
                ('user_ticket', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
